# Reward/persona presets for DoodleJumpEnv

survivor:
  REWARD_LAND: 0.6
  REWARD_CLIMB_SCALE: 1.5
  REWARD_CLIMB_CAP: 6.0
  REWARD_COIN: 5.0
  REWARD_KILL: 2.0
  PENALTY_DEATH: -7.0
  PENALTY_IDLE: -0.12
  PENALTY_PLATFORM_TIME: -0.03
  REWARD_HEIGHT_BONUS: 0.005
  REWARD_UPWARD_MOTION: 0.02
  COIN_SPAWN_P: 0.22
  ENEMY_SPAWN_P: 0.14
  PLATFORM_W: 120
  GAP_MIN: 36
  GAP_MAX: 72
